# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.18.6

# Mod Properties
mod_version=2.8.4
maven_group=red.jackf
archives_base_name=chesttracker

# Dependencies
bundle_searchables=true
searchables_version=26.1.2:1.0.1

# Mod Compat
# clothconfig_version=21.11.152
shulkerboxtooltip_version=5.2.18+26.1
wthit_version=fabric-19.0.0
badpackets_version=fabric-0.12.1
jade_version=26.0.4+fabric
yacl_version=3.9.1+26.1-fabric
# litematica_version=0.25.2
# malilib_version=0.27.2

# JF_AUTO_UPDATE_BLOCK
fabric-api_version=0.145.4+26.1.2
modmenu_version=18.0.0
where-is-it_version=2.7.4+26.1
# emi_version=1.1.12+1.21
# JF_END_AUTO_UPDATE_BLOCK

# Publishing
game_versions_mr=26.1.2
game_versions_curse=26.1.2

prefix=[26.1.2]
release_type=release
changelog_filter=[feat],[fix],[change],[update],[docs],[translations]
mod_name=Chest Tracker (Unofficial port)
github_owner=ponuing
github_repo=ChestTracker
github_url=https://github.com/ponuing/ChestTracker
